- ros_topic_name: "/lidar_left"
  gz_topic_name: "/lidar_left"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL # BIDIRECTIONAL or ROS_TO_IGN
- ros_topic_name: "/lidar_right"
  gz_topic_name: "/lidar_right"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: BIDIRECTIONAL # BIDIRECTIONAL or ROS_TO_IGN
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: BIDIRECTIONAL # BIDIRECTIONAL or ROS_TO_IGN
